// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Categories = sequelize.define('categories', {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    eventkey: {
      type: DataTypes.STRING,
      allowNull: false,
    },
  }, {
    tableName: 'categories',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Categories.associate = (models) => {
    Categories.belongsTo(models.programs, {
      foreignKey: {
        name: 'programsIdKey',
        field: 'programs_id',
      },
      as: 'programs',
    });
    Categories.hasMany(models.subcategories, {
      foreignKey: {
        name: 'categoriesIdKey',
        field: 'categories_id',
      },
      as: 'categoriesSubcategories',
    });
  };

  return Categories;
};
