// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Gisus = sequelize.define('gisus', {
    gisu: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'gisus',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Gisus.associate = (models) => {
    Gisus.belongsTo(models.programs, {
      foreignKey: {
        name: 'programsIdKey',
        field: 'programs_id',
      },
      as: 'programs',
    });
    Gisus.hasMany(models.stepsCalendars, {
      foreignKey: {
        name: 'gisusIdKey',
        field: 'gisus_id',
      },
      as: 'stepsCalendars',
    });
    Gisus.hasMany(models.stepsTimelines, {
      foreignKey: {
        name: 'gisusIdKey',
        field: 'gisus_id',
      },
      as: 'stepsTimelines',
    });
  };

  return Gisus;
};
