// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Qnas = sequelize.define('qnas', {
    q: {
      type: DataTypes.STRING,
    },
    a: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'qnas',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Qnas.associate = (models) => {
    Qnas.belongsTo(models.subcategories, {
      foreignKey: {
        name: 'subcategoriesIdKey',
        field: 'subcategories_id',
      },
      as: 'subcategories',
    });
  };

  return Qnas;
};
