// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Subcategories = sequelize.define('subcategories', {
    title: {
      type: DataTypes.STRING,
    },
    link: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'subcategories',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Subcategories.associate = (models) => {
    Subcategories.belongsTo(models.categories, {
      foreignKey: {
        name: 'categoriesIdKey',
        field: 'categories_id',
      },
      as: 'categories',
    });
    Subcategories.hasMany(models.qnas, {
      foreignKey: {
        name: 'subcategoriesIdKey',
        field: 'subcategories_id',
      },
      as: 'subcategoriesQnas',
    });
  };

  return Subcategories;
};
